[package]
org = "ballerinax"
name = "cdata.connect"
version = "1.0.0"
authors = ["Ballerina"]
keywords = ["IT Operations/Cloud Services", "Cost/Paid"]
repository = "https://github.com/ballerina-platform/module-ballerinax-cdata.connect"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.1"

[[platform.java11.dependency]]
path = "../native/build/libs/cdata.connect-native-1.0.0.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.3.1.jar"
